package vn.cinema.service;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.jdbc.core.JdbcTemplate;import vn.cinema.client.*;import vn.cinema.repository.ShowtimeRepository;import vn.cinema.entity.Showtime;import vn.cinema.dto.ShowtimeRequest;import vn.cinema.exception.Problem;import java.util.*;import java.time.*;
@Service public class ShowtimeService{private final ShowtimeRepository repo;private final MovieClient movies;private final CinemaClient cinemas;private final BookingClient bookings;private final JdbcTemplate db;public ShowtimeService(ShowtimeRepository r,MovieClient m,CinemaClient c,BookingClient b,JdbcTemplate d){repo=r;movies=m;cinemas=c;bookings=b;db=d;}
 public Showtime get(long id){return repo.findById(id).orElseThrow(Problem::missing);}public List<Showtime> list(Long movieId,Long cinemaId,Long roomId,LocalDate date,String status){return repo.findAll().stream().filter(s->movieId==null||s.movieId.equals(movieId)).filter(s->cinemaId==null||s.cinemaId.equals(cinemaId)).filter(s->roomId==null||s.roomId.equals(roomId)).filter(s->date==null||s.showDate.equals(date)).filter(s->status==null||status.isBlank()||s.status.equals(status)).sorted(Comparator.comparing(s->s.startAt)).toList();}
 @Transactional public Object openBooking(long id){var s=repo.lock(id).orElseThrow(Problem::missing);s.bookingOpened=true;return details(id);}public Object details(long id){var s=get(id);return Map.of("showtime",s,"movie",movies.get(s.movieId),"cinema",cinemas.cinema(s.cinemaId),"room",cinemas.room(s.roomId));}
 @Transactional public Showtime save(Long id,ShowtimeRequest r){
 var movie=movies.get(r.movieId());var cinema=cinemas.cinema(r.cinemaId());var room=cinemas.room(r.roomId());if(room.path("cinemaId").asLong()!=r.cinemaId())throw new Problem(400,"Phòng không thuộc rạp đã chọn");if(!room.path("status").asText().equals("ACTIVE")||!cinema.path("status").asText().equals("ACTIVE")||movie.path("status").asText().equals("STOPPED"))throw new Problem(400,"Phim, rạp hoặc phòng đang ngừng hoạt động");
 if(r.showDate().isBefore(LocalDate.parse(movie.path("releaseDate").asText()))||r.showDate().isAfter(LocalDate.parse(movie.path("endDate").asText())))throw new Problem(400,"Ngày chiếu ngoài thời gian phát hành");
 var start=LocalDateTime.of(r.showDate(),r.startTime());if(start.isBefore(LocalDateTime.now()))throw new Problem(400,"Suất chiếu phải ở tương lai");var end=start.plusMinutes(movie.path("duration").asInt());
 db.update("INSERT IGNORE INTO room_guard(id) VALUES (?)",r.roomId());db.queryForObject("SELECT id FROM room_guard WHERE id=? FOR UPDATE",Long.class,r.roomId());
 if(id!=null&&(repo.lock(id).orElseThrow(Problem::missing).bookingOpened||bookings.used(id)))throw new Problem(409,"Suất chiếu đã có đặt vé, không thể sửa");if(repo.overlapping(r.roomId(),start,end).stream().anyMatch(s->!s.id.equals(id)))throw new Problem(409,"Lịch chiếu trùng trong cùng phòng");
 var s=id==null?new Showtime():get(id);s.movieId=r.movieId();s.cinemaId=r.cinemaId();s.roomId=r.roomId();s.showDate=r.showDate();s.startTime=r.startTime();s.endTime=end.toLocalTime();s.startAt=start;s.endAt=end;s.basePrice=r.basePrice();s.status=r.status();return repo.save(s);}
 @Transactional public void delete(long id){if(repo.lock(id).orElseThrow(Problem::missing).bookingOpened||bookings.used(id))throw new Problem(409,"Suất chiếu đã có đặt vé");repo.delete(get(id));}public boolean movieUsed(long id){return repo.existsByMovieId(id);}public boolean roomUsed(long id){return repo.existsByRoomId(id);}
}
