package vn.cinema.service;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import vn.cinema.repository.*;import vn.cinema.entity.*;import vn.cinema.dto.MovieRequest;import vn.cinema.exception.Problem;import vn.cinema.client.ShowtimeClient;import java.util.*;
@Service public class MovieService{private final MovieRepository movies;private final CategoryRepository categories;private final ShowtimeClient schedules;public MovieService(MovieRepository m,CategoryRepository c,ShowtimeClient s){movies=m;categories=c;schedules=s;}
 public Movie get(long id){return movies.findById(id).orElseThrow(Problem::missing);}public List<Movie> list(String q,String status,Long categoryId){return movies.findAll().stream().filter(m->q==null||m.title.toLowerCase(Locale.ROOT).contains(q.toLowerCase(Locale.ROOT))).filter(m->status==null||status.isBlank()||m.status.equals(status)).filter(m->categoryId==null||m.categories.stream().anyMatch(c->c.id.equals(categoryId))).toList();}
 @Transactional public Movie save(Long id,MovieRequest r){if(r.endDate().isBefore(r.releaseDate()))throw new Problem(400,"Ngày kết thúc phải sau ngày khởi chiếu");Movie x=id==null?new Movie():get(id);x.title=r.title();x.originalTitle=r.originalTitle();x.description=r.description();x.duration=r.duration();x.releaseDate=r.releaseDate();x.endDate=r.endDate();x.ageRating=r.ageRating();x.language=r.language();x.country=r.country();x.director=r.director();x.actors=r.actors();x.posterUrl=r.posterUrl();x.bannerUrl=r.bannerUrl();x.trailerUrl=r.trailerUrl();x.status=r.status();x.categories=new LinkedHashSet<>();for(Long cid:r.categoryIds())x.categories.add(categories.findById(cid).orElseThrow(Problem::missing));return movies.save(x);}
 @Transactional public void delete(long id){if(schedules.movieUsed(id))throw new Problem(409,"Phim đã có lịch chiếu. Hãy chuyển sang Ngừng chiếu");movies.delete(get(id));}
 public List<Category> categories(){return categories.findAll();}
 @Transactional public Category category(Long id,String name,String description){Category c=id==null?new Category():categories.findById(id).orElseThrow(Problem::missing);c.name=name;c.description=description;return categories.save(c);}
 @Transactional public void deleteCategory(long id){if(movies.existsByCategoriesId(id))throw new Problem(409,"Thể loại đang được phim sử dụng");categories.delete(categories.findById(id).orElseThrow(Problem::missing));}
}