package vn.cinema.gateway;
import org.springframework.stereotype.Component;import org.springframework.cloud.gateway.filter.*;import org.springframework.core.Ordered;import org.springframework.web.server.ServerWebExchange;import reactor.core.publisher.Mono;import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;import org.springframework.web.reactive.function.client.WebClient;import org.springframework.beans.factory.annotation.Value;
@Component public class GatewayGuard implements GlobalFilter,Ordered{
 private final WebClient auth;private final String key;public GatewayGuard(@Value("${app.internal-key}")String key){this.key=key;this.auth=WebClient.create("http://localhost:8081");}
 public int getOrder(){return -100;}
 public Mono<Void> filter(ServerWebExchange exchange,GatewayFilterChain chain){var clean=exchange.mutate().request(r->r.headers(h->{h.remove("X-User-Id");h.remove("X-User-Role");h.remove("X-Internal-Key");})).build();
 return exchange.getPrincipal().map(p->p instanceof JwtAuthenticationToken t?java.util.Optional.of(t):java.util.Optional.<JwtAuthenticationToken>empty()).defaultIfEmpty(java.util.Optional.empty()).flatMap(opt->{if(opt.isEmpty())return chain.filter(clean);var jwt=opt.get().getToken();return auth.get().uri("/internal/users/"+jwt.getClaim("userId")).header("X-Internal-Key",key).retrieve().bodyToMono(com.fasterxml.jackson.databind.JsonNode.class).flatMap(user->{if(!"ACTIVE".equals(user.path("status").asText()))return error(exchange,401,"Tài khoản đã bị khóa");return chain.filter(clean.mutate().request(r->r.header("X-User-Id",jwt.getClaim("userId").toString()).header("X-User-Role",jwt.getClaimAsString("role"))).build());}).onErrorResume(e->error(exchange,503,"Dịch vụ xác thực chưa sẵn sàng"));});}
 static Mono<Void> error(ServerWebExchange e,int code,String message){e.getResponse().setStatusCode(org.springframework.http.HttpStatus.valueOf(code));e.getResponse().getHeaders().setContentType(org.springframework.http.MediaType.APPLICATION_JSON);return e.getResponse().writeWith(Mono.just(e.getResponse().bufferFactory().wrap(("{\"success\":false,\"message\":\""+message+"\",\"data\":null}").getBytes(java.nio.charset.StandardCharsets.UTF_8))));}
}
