package vn.cinema.controller;
import org.springframework.web.bind.annotation.*;import jakarta.validation.Valid;import vn.cinema.dto.*;import vn.cinema.service.ShowtimeService;import java.time.LocalDate;
@RestController public class ShowtimeController{private final ShowtimeService s;public ShowtimeController(ShowtimeService s){this.s=s;}
 @GetMapping({"/api/showtimes","/api/showtimes/filter"})public Object list(@RequestParam(required=false)Long movieId,@RequestParam(required=false)Long cinemaId,@RequestParam(required=false)Long roomId,@RequestParam(required=false)LocalDate date,@RequestParam(required=false)String status){return Api.ok(s.list(movieId,cinemaId,roomId,date,status));}
 @GetMapping("/api/showtimes/movie/{id}")public Object movie(@PathVariable long id){return Api.ok(s.list(id,null,null,null,null));}@GetMapping("/api/showtimes/cinema/{id}")public Object cinema(@PathVariable long id){return Api.ok(s.list(null,id,null,null,null));}
 @GetMapping("/api/showtimes/{id}")public Object get(@PathVariable long id){return Api.ok(s.get(id));}@GetMapping("/api/showtimes/{id}/details")public Object details(@PathVariable long id){return Api.ok(s.details(id));}
 @PostMapping("/api/showtimes")public Object create(@Valid @RequestBody ShowtimeRequest r){return Api.ok(s.save(null,r));}@PutMapping("/api/showtimes/{id}")public Object update(@PathVariable long id,@Valid @RequestBody ShowtimeRequest r){return Api.ok(s.save(id,r));}@DeleteMapping("/api/showtimes/{id}")public Object delete(@PathVariable long id){s.delete(id);return Api.ok("Đã xóa suất chiếu");}
 @PostMapping("/internal/showtimes/{id}/open-booking")public Object openBooking(@PathVariable long id){return s.openBooking(id);}@GetMapping("/internal/showtimes/{id}")public Object internal(@PathVariable long id){return s.get(id);}@GetMapping("/internal/showtimes/{id}/details")public Object internalDetails(@PathVariable long id){return s.details(id);}@GetMapping("/internal/showtimes/movie/{id}/exists")public boolean usedMovie(@PathVariable long id){return s.movieUsed(id);}@GetMapping("/internal/showtimes/room/{id}/exists")public boolean usedRoom(@PathVariable long id){return s.roomUsed(id);}
}
