CREATE DATABASE IF NOT EXISTS cinema_auth_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'cinema_auth'@'localhost' IDENTIFIED BY 'CinemaLocal_2026!';
GRANT ALL PRIVILEGES ON cinema_auth_db.* TO 'cinema_auth'@'localhost';
CREATE DATABASE IF NOT EXISTS cinema_movie_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'cinema_movie'@'localhost' IDENTIFIED BY 'CinemaLocal_2026!';
GRANT ALL PRIVILEGES ON cinema_movie_db.* TO 'cinema_movie'@'localhost';
CREATE DATABASE IF NOT EXISTS cinema_cinema_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'cinema_cinema'@'localhost' IDENTIFIED BY 'CinemaLocal_2026!';
GRANT ALL PRIVILEGES ON cinema_cinema_db.* TO 'cinema_cinema'@'localhost';
CREATE DATABASE IF NOT EXISTS cinema_showtime_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'cinema_showtime'@'localhost' IDENTIFIED BY 'CinemaLocal_2026!';
GRANT ALL PRIVILEGES ON cinema_showtime_db.* TO 'cinema_showtime'@'localhost';
CREATE DATABASE IF NOT EXISTS cinema_booking_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'cinema_booking'@'localhost' IDENTIFIED BY 'CinemaLocal_2026!';
GRANT ALL PRIVILEGES ON cinema_booking_db.* TO 'cinema_booking'@'localhost';
CREATE DATABASE IF NOT EXISTS cinema_payment_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'cinema_payment'@'localhost' IDENTIFIED BY 'CinemaLocal_2026!';
GRANT ALL PRIVILEGES ON cinema_payment_db.* TO 'cinema_payment'@'localhost';
CREATE DATABASE IF NOT EXISTS cinema_notification_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'cinema_notification'@'localhost' IDENTIFIED BY 'CinemaLocal_2026!';
GRANT ALL PRIVILEGES ON cinema_notification_db.* TO 'cinema_notification'@'localhost';
