import {useEffect,useState,createContext,useContext,type ReactNode} from 'react';
import {Navigate,useLocation,Link} from 'react-router-dom';
import {AnimatePresence,motion} from 'framer-motion';
import {X,ImageIcon,LoaderCircle,Upload,Check} from 'lucide-react';
import toast from 'react-hot-toast';
import {api,get,asset,errorText,money} from './api/axiosClient';
export type Row=Record<string,any>;
export const Session=createContext<{user:Row|null,loading:boolean,refresh:()=>Promise<void>,logout:()=>void}>({user:null,loading:true,refresh:async()=>{},logout:()=>{localStorage.removeItem('cinema-token');}});
export const useSession=()=>useContext(Session);
export function useData<T=any>(url:string|undefined){const [data,setData]=useState<T|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [version,setVersion]=useState(0);useEffect(()=>{let active=true;setLoading(true);setError('');if(!url){setLoading(false);return;}get<T>(url).then(x=>{if(active)setData(x);}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[url,version]);return {data,loading,error,reload:()=>setVersion(v=>v+1),setData};}
export function Skeleton(){return <div className="skeleton-grid" aria-label="Đang tải dữ liệu">{[0,1,2,3].map(i=><div className="skeleton" key={i}/>)}</div>;}
export function ErrorBox({message,retry}:{message:string,retry:()=>void}){return <div role="alert" className="empty"><h3>Chưa tải được dữ liệu</h3><p>{message}</p><button onClick={retry}>Thử lại</button></div>;}
export function Empty({text='Chưa có dữ liệu phù hợp'}:{text?:string}){return <div className="empty"><ImageIcon size={32}/><p>{text}</p></div>;}
export function ProtectedRoute({children}:{children:ReactNode}){const {user,loading}=useSession();const l=useLocation();if(loading)return <Skeleton/>;return user?children:<Navigate to={'/login?next='+encodeURIComponent(l.pathname+l.search)} replace/>;}
export function AdminRoute({children}:{children:ReactNode}){const {user,loading}=useSession();if(loading)return <Skeleton/>;return user?.role==='ADMIN'?children:user?<Navigate to="/unauthorized" replace/>:<Navigate to="/login?next=/admin" replace/>;}
export function GuestRoute({children}:{children:ReactNode}){const {user,loading}=useSession();if(loading)return <Skeleton/>;return user?<Navigate to="/" replace/>:children;}
export function Poster({src,alt,className=''}:{src?:string,alt:string,className?:string}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return src&&!failed?<img className={'poster '+className} src={asset(src)} alt={alt} loading="lazy" onError={()=>setFailed(true)}/>:<div className={'poster placeholder '+className}><ImageIcon/><span>Ảnh đang cập nhật</span></div>;}
export function Button({busy,children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{busy?:boolean}){return <motion.button whileHover={{scale:1.02}} whileTap={{scale:.96}} {...props as any} disabled={busy||props.disabled}>{busy?<LoaderCircle className="spin" size={18}/>:null}{children}</motion.button>;}
export function Modal({title,children,onClose}:{title:string,children:ReactNode,onClose:()=>void}){useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',handler);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=previous;};},[onClose]);return <AnimatePresence><motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><motion.section role="dialog" aria-modal="true" aria-label={title} className="modal" initial={{scale:.95,y:12}} animate={{scale:1,y:0}} transition={{type:'spring',duration:.3}}><div className="section-head"><h2>{title}</h2><button className="icon-button" aria-label="Đóng" onClick={onClose}><X/></button></div>{children}</motion.section></motion.div></AnimatePresence>;}
export const labels:Record<string,string>={PENDING:'Chờ thanh toán',CONFIRMED:'Đã xác nhận',CANCELLED:'Đã hủy',EXPIRED:'Đã hết hạn',SUCCESS:'Thành công',FAILED:'Thất bại',REFUNDED:'Đã hoàn tiền',NORMAL:'Ghế thường',VIP:'Ghế VIP',COUPLE:'Ghế đôi',ACTIVE:'Hoạt động',INACTIVE:'Ngừng hoạt động',LOCKED:'Đã khóa',AVAILABLE:'Còn chỗ',FULL:'Hết chỗ',FINISHED:'Đã kết thúc',NOW_SHOWING:'Đang chiếu',COMING_SOON:'Sắp chiếu',STOPPED:'Ngừng chiếu',USER:'Khách hàng',ADMIN:'Quản trị viên',STANDARD:'Tiêu chuẩn',IMAX:'IMAX',QR_CODE:'Mã QR',PAYOS:'payOS'};
export function Badge({status}:{status:string}){return <span className={'badge '+status?.toLowerCase()}>{labels[status]||status}</span>;}
export function Countdown({until,onExpired}:{until:string,onExpired?:()=>void}){const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);const seconds=Math.max(0,Math.ceil((Date.parse(until)-now)/1000));useEffect(()=>{if(seconds===0)onExpired?.();},[seconds]);return <span className={seconds<60?'countdown urgent':'countdown'}>{seconds===0?'Đã hết thời gian giữ ghế':'Còn '+Math.floor(seconds/60).toString().padStart(2,'0')+':'+(seconds%60).toString().padStart(2,'0')}</span>;}
export function PriceTable({seats,total}:{seats:Row[],total:number}){return <div className="price-table"><div className="price-row muted"><span>Ghế</span><span>Loại ghế</span><span>Đơn giá</span></div>{seats.map(s=><div className="price-row" key={s.seatId??s.id}><strong>{s.seatName||s.rowName+s.seatNumber}</strong><span>{labels[s.seatType]}</span><strong>{money(s.unitPrice)}</strong></div>)}<div className="total"><span>Tổng thanh toán</span><strong>{money(total)}</strong></div></div>;}
export function UploadField({label,value,onChange,type}:{label:string,value:string,onChange:(v:string)=>void,type:string}){const [progress,setProgress]=useState<number|null>(null);const [preview,setPreview]=useState('');useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);async function upload(file?:File){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){toast.error('Chọn ảnh JPG, PNG hoặc WEBP, tối đa 5MB');return;}setPreview(URL.createObjectURL(file));setProgress(0);const form=new FormData();form.append('file',file);form.append('type',type);try{const r=await api.post('/api/uploads/images',form,{onUploadProgress:e=>setProgress(Math.round((e.loaded/(e.total||file.size))*100))});onChange(r.data.data.url);toast.success('Upload ảnh thành công');}catch(e){setPreview('');toast.error(errorText(e));}finally{setProgress(null);}}return <div className="upload-field"><label>{label}</label><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files[0]);}}>{preview||value?<Poster src={preview||value} alt={label}/>:<Upload/>}<label className="upload-button">{value?'Đổi ảnh':'Chọn ảnh từ máy tính'}<input aria-label={'Upload '+label} type="file" accept="image/jpeg,image/png,image/webp" disabled={progress!==null} onChange={e=>void upload(e.target.files?.[0])}/></label><small>JPG, PNG, WEBP • tối đa 5MB</small>{progress!==null?<progress value={progress} max="100"/>:value?<span className="success-text"><Check size={14}/>Đã tải ảnh</span>:null}</div><input aria-label={'URL '+label} type="text" placeholder="Hoặc nhập URL ảnh" value={value} onChange={e=>{setPreview('');onChange(e.target.value);}}/>{value&&<button type="button" className="text-button" onClick={()=>{setPreview('');onChange('');}}>Xóa ảnh đã chọn</button>}</div>;}
