package vn.cinema.service;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import vn.cinema.entity.*;import vn.cinema.repository.*;import vn.cinema.dto.CinemaRequests.*;import vn.cinema.client.ShowtimeClient;import vn.cinema.exception.Problem;import java.util.*;
@Service public class CinemaService{private final CinemaRepository cinemas;private final RoomRepository rooms;private final SeatRepository seats;private final ShowtimeClient schedules;public CinemaService(CinemaRepository c,RoomRepository r,SeatRepository s,ShowtimeClient t){cinemas=c;rooms=r;seats=s;schedules=t;}
 public List<Cinema> cinemas(){return cinemas.findAll();}public Cinema cinema(long id){return cinemas.findById(id).orElseThrow(Problem::missing);}public List<Room> rooms(){return rooms.findAll();}public Room room(long id){return rooms.findById(id).orElseThrow(Problem::missing);}public List<Seat> seats(long id){room(id);return seats.findByRoomIdOrderByRowNameAscSeatNumberAsc(id);}
 @Transactional public Cinema saveCinema(Long id,CinemaInput r){var x=id==null?new Cinema():cinema(id);x.name=r.name();x.address=r.address();x.province=r.province();x.phone=r.phone();x.description=r.description();x.imageUrl=r.imageUrl();x.status=r.status();return cinemas.save(x);}
 @Transactional public Room saveRoom(Long id,RoomInput r){cinema(r.cinemaId());var x=id==null?new Room():room(id);if(id!=null&&(!x.cinemaId.equals(r.cinemaId())||!x.roomType.equals(r.roomType()))&&schedules.roomUsed(id))throw new Problem(409,"Phòng đã có lịch chiếu, không thể thay đổi rạp hoặc loại phòng");x.cinemaId=r.cinemaId();x.name=r.name();x.roomType=r.roomType();x.status=r.status();if(id==null)x.totalSeats=0;return rooms.save(x);}
 @Transactional public List<Seat> generate(long id,Generate r){var room=room(id);if(!seats(id).isEmpty())throw new Problem(409,"Phòng đã có ghế; hãy chỉnh sửa trên sơ đồ");var list=new ArrayList<Seat>();for(int row=0;row<r.rows();row++)for(int col=1;col<=r.columns();col++){var s=new Seat();s.roomId=id;s.rowName=String.valueOf((char)('A'+row));s.seatNumber=col;s.seatType=row>=4&&row<7?"VIP":"NORMAL";s.status="ACTIVE";list.add(s);}room.totalSeats=list.size();return seats.saveAll(list);}
 @Transactional public Seat seat(long id,SeatInput r){var s=seats.findById(id).orElseThrow(Problem::missing);s.seatType=r.seatType();s.status=r.status();return s;}
 @Transactional public void deleteCinema(long id){if(!rooms.findByCinemaId(id).isEmpty())throw new Problem(409,"Rạp đang có phòng chiếu");cinemas.delete(cinema(id));}
 @Transactional public void deleteRoom(long id){if(schedules.roomUsed(id))throw new Problem(409,"Phòng đã có lịch chiếu");seats.deleteAll(seats(id));rooms.delete(room(id));}
}