package vn.cinema.service;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.beans.factory.annotation.Value;import org.springframework.security.oauth2.jwt.*;import org.springframework.security.oauth2.jose.jws.MacAlgorithm;import com.nimbusds.jose.jwk.source.ImmutableSecret;import java.nio.charset.StandardCharsets;import java.time.Instant;import java.util.*;import vn.cinema.dto.AuthRequests.*;import vn.cinema.entity.User;import vn.cinema.repository.UserRepository;import vn.cinema.exception.Problem;
@Service public class AuthService{
 private final UserRepository users;private final BCryptPasswordEncoder passwords=new BCryptPasswordEncoder();private final JwtEncoder encoder;
 public AuthService(UserRepository users,@Value("${app.jwt-secret}")String secret){this.users=users;encoder=new NimbusJwtEncoder(new ImmutableSecret<>(secret.getBytes(StandardCharsets.UTF_8)));}
 @Transactional public User register(Register r){String email=r.email().trim().toLowerCase(Locale.ROOT);if(users.findByEmail(email).isPresent())throw new Problem(409,"Email đã được sử dụng");var u=new User();u.fullName=r.fullName().trim();u.email=email;u.phone=r.phone();u.password=passwords.encode(r.password());return users.saveAndFlush(u);}
 public Map<String,Object> login(Login r){var u=users.findByEmail(r.email().trim().toLowerCase(Locale.ROOT)).orElseThrow(()->new Problem(401,"Email hoặc mật khẩu không đúng"));if(!passwords.matches(r.password(),u.password))throw new Problem(401,"Email hoặc mật khẩu không đúng");if(!u.status.equals("ACTIVE"))throw new Problem(403,"Tài khoản đã bị khóa");var now=Instant.now();var claims=JwtClaimsSet.builder().issuer("cinema").subject(u.id.toString()).issuedAt(now).expiresAt(now.plusSeconds(86400)).claim("userId",u.id).claim("email",u.email).claim("role",u.role).build();String token=encoder.encode(JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(),claims)).getTokenValue();return Map.of("token",token,"user",u);}
 public User get(long id){return users.findById(id).orElseThrow(Problem::missing);}
 @Transactional public User profile(long id,Profile r){var u=get(id);u.fullName=r.fullName();u.phone=r.phone();u.avatarUrl=r.avatarUrl();return u;}
 @Transactional public void password(long id,Password r){var u=get(id);if(!passwords.matches(r.oldPassword(),u.password))throw new Problem(400,"Mật khẩu hiện tại không đúng");u.password=passwords.encode(r.newPassword());}
 @Transactional public User status(long id,String status){if(id==vn.cinema.security.Actor.id())throw new Problem(409,"Không thể tự khóa tài khoản quản trị");var u=get(id);u.status=status;return u;}
 public List<User> list(){return users.findAll();}
}