import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=process.env.API_URL||'http://localhost:8080';
const reports=[];
async function request(path,{method='GET',data,token,status=200,form}={}){const r=await fetch(base+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(!form&&data?{'Content-Type':'application/json'}:{})},body:form|| (data?JSON.stringify(data):undefined),signal:AbortSignal.timeout(30000)});const body=await r.json();assert.equal(r.status,status,path+' '+JSON.stringify(body));return body.data;}
async function check(name,fn){await fn();reports.push({name,status:'PASS'});console.log('PASS',name);}
const login=async(email,password='123456')=>request('/api/auth/login',{method:'POST',data:{email,password}});
let user,admin,other,show,booking,payment;
try{
 await check('Register and reject duplicate email',async()=>{const email='e2e-'+Date.now()+'@example.com';await request('/api/auth/register',{method:'POST',data:{fullName:'Khách kiểm thử',email,password:'123456'},status:201});await request('/api/auth/register',{method:'POST',data:{fullName:'Khách kiểm thử',email,password:'123456'},status:409});other=await login(email);});
 await check('Login and reject wrong password',async()=>{user=await login('user@gmail.com');admin=await login('admin@gmail.com');await request('/api/auth/login',{method:'POST',data:{email:'user@gmail.com',password:'wrong-password'},status:401});});
 await check('Reject forged identity and user admin write',async()=>{const r=await fetch(base+'/api/bookings',{method:'POST',headers:{'Content-Type':'application/json','X-User-Id':'1','X-User-Role':'ADMIN'},body:'{}'});assert.equal(r.status,401);await request('/api/categories',{method:'POST',token:user.token,data:{name:'Forbidden',description:''},status:403});});
 let normal,vip;
 await check('Read live movies, cinemas, showtimes and seat prices',async()=>{assert.ok((await request('/api/movies')).length>=10);assert.ok((await request('/api/cinemas')).length>=3);const shows=await request('/api/showtimes');for(const s of shows){if(s.status!=='AVAILABLE'||new Date(s.startAt)<new Date())continue;const map=await request('/api/bookings/showtime/'+s.id+'/seats',{token:user.token});normal=map.seats.find(x=>x.seatType==='NORMAL'&&x.availability==='AVAILABLE');vip=map.seats.find(x=>x.seatType==='VIP'&&x.availability==='AVAILABLE');if(normal&&vip){show=s;assert.equal(normal.unitPrice,s.basePrice);assert.equal(vip.unitPrice,s.basePrice+30000);break;}}assert.ok(show,'No available seats in demo data');});
 await check('Create booking with server prices',async()=>{booking=await request('/api/bookings',{method:'POST',token:user.token,data:{showtimeId:show.id,seatIds:[normal.id,vip.id]},status:201});assert.equal(booking.status,'PENDING');assert.equal(booking.totalAmount,normal.unitPrice+vip.unitPrice);assert.equal(booking.seats.length,2);});
 await check('Reject duplicate booking and wrong owner',async()=>{await request('/api/bookings',{method:'POST',token:other.token,data:{showtimeId:show.id,seatIds:[normal.id]},status:409});await request('/api/bookings/'+booking.id,{token:other.token,status:403});});
 await check('Create payOS payment, leave, reopen, and resume same payment',async()=>{payment=await request('/api/payments',{method:'POST',token:user.token,data:{bookingId:booking.id,paymentMethod:'PAYOS'}});assert.ok(payment.providerPaymentLinkId&&payment.qrContent);await request('/api/movies');const tickets=await request('/api/bookings',{token:user.token});assert.ok(tickets.some(b=>b.id===booking.id&&b.status==='PENDING'));const reopened=await request('/api/bookings/'+booking.id,{token:user.token});assert.equal(reopened.expiredAt,booking.expiredAt);const resumed=await request('/api/payments/booking/'+booking.id,{token:user.token});const recreated=await request('/api/payments',{method:'POST',token:user.token,data:{bookingId:booking.id,paymentMethod:'PAYOS'}});assert.equal(resumed.id,payment.id);assert.equal(recreated.id,payment.id);assert.equal(resumed.qrContent,payment.qrContent);});
 await check('Admin fallback confirmation is idempotent',async()=>{const results=await Promise.all(Array.from({length:5},()=>request('/api/payments/'+payment.id+'/confirm',{method:'POST',token:admin.token})));assert.ok(results.every(p=>p.id===payment.id&&p.status==='SUCCESS'));const b=await request('/api/bookings/'+booking.id,{token:user.token});assert.equal(b.status,'CONFIRMED');await request('/api/bookings/'+booking.id+'/cancel',{method:'PUT',token:user.token,status:409});});
 await check('Notification delivered exactly once',async()=>{let found=[];for(let i=0;i<12;i++){found=(await request('/api/notifications',{token:user.token})).filter(n=>n.bookingId===booking.id);if(found.length)break;await new Promise(r=>setTimeout(r,1000));}assert.equal(found.length,1);await request('/api/notifications/'+found[0].id+'/read',{method:'PUT',token:user.token});});
 await check('Cancel payOS payment and release seats',async()=>{const map=await request('/api/bookings/showtime/'+show.id+'/seats',{token:user.token});const seat=map.seats.find(x=>x.availability==='AVAILABLE');const b=await request('/api/bookings',{method:'POST',token:user.token,data:{showtimeId:show.id,seatIds:[seat.id]},status:201});const p=await request('/api/payments',{method:'POST',token:user.token,data:{bookingId:b.id,paymentMethod:'PAYOS'}});await request('/api/payments/'+p.id+'/cancel',{method:'POST',token:user.token});assert.equal((await request('/api/payments/'+p.id,{token:user.token})).status,'FAILED');const after=await request('/api/bookings/showtime/'+show.id+'/seats',{token:user.token});assert.equal(after.seats.find(s=>s.id===seat.id).availability,'AVAILABLE');});
 await check('Admin CRUD category, cinema, room, seats, movie, showtime',async()=>{const token=admin.token;const tag=Date.now();const cat=await request('/api/categories',{method:'POST',token,data:{name:'Kiểm thử '+tag,description:'E2E'}});const cinema=await request('/api/cinemas',{method:'POST',token,data:{name:'Rạp E2E '+tag,province:'Hà Nội',address:'Địa chỉ kiểm thử',phone:'0900000000',description:'E2E',imageUrl:'',status:'ACTIVE'}});const room=await request('/api/rooms',{method:'POST',token,data:{cinemaId:cinema.id,name:'Phòng E2E',totalSeats:0,roomType:'STANDARD',status:'ACTIVE'}});const seats=await request('/api/rooms/'+room.id+'/generate-seats',{method:'POST',token,data:{rows:8,columns:8}});assert.equal(seats.length,64);await request('/api/seats/'+seats[0].id,{method:'PUT',token,data:{seatType:'VIP',status:'LOCKED'}});const today=new Date();today.setDate(today.getDate()+2);const date=today.toISOString().slice(0,10);const input={title:'Phim E2E '+tag,originalTitle:'E2E',description:'Kiểm thử toàn bộ API',duration:120,releaseDate:date,endDate:date,ageRating:'P',language:'Tiếng Việt',country:'Việt Nam',director:'Kiểm thử',actors:'Kiểm thử',posterUrl:'',bannerUrl:'',trailerUrl:'',status:'NOW_SHOWING',categoryIds:[cat.id]};const movie=await request('/api/movies',{method:'POST',token,data:input});await request('/api/movies/'+movie.id,{method:'PUT',token,data:{...input,title:input.title+' cập nhật'}});await request('/api/categories/'+cat.id,{method:'DELETE',token,status:409});const schedule={movieId:movie.id,cinemaId:cinema.id,roomId:room.id,showDate:date,startTime:'18:00',basePrice:90000,status:'AVAILABLE'};const st=await request('/api/showtimes',{method:'POST',token,data:schedule});assert.equal(st.endTime.slice(0,5),'20:00');const persisted=await request('/api/showtimes/'+st.id);assert.equal(persisted.startTime.slice(0,5),'18:00');assert.equal(persisted.endTime.slice(0,5),'20:00');assert.equal(persisted.showDate,date);assert.equal(persisted.startAt.slice(0,16),date+'T18:00');await request('/api/showtimes',{method:'POST',token,data:{...schedule,startTime:'19:00'},status:409});await request('/api/showtimes/'+st.id,{method:'DELETE',token});await request('/api/movies/'+movie.id,{method:'DELETE',token});await request('/api/categories/'+cat.id,{method:'DELETE',token});await request('/api/rooms/'+room.id,{method:'DELETE',token});await request('/api/cinemas/'+cinema.id,{method:'DELETE',token});});
 await check('Upload PNG, serve bytes, preserve URL across profile reload',async()=>{const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a7h8AAAAASUVORK5CYII=','base64');const form=new FormData();form.append('file',new Blob([bytes],{type:'image/png'}),'avatar.png');form.append('type','AVATAR');const image=await request('/api/uploads/images',{method:'POST',token:user.token,form});await request('/api/auth/profile',{method:'PUT',token:user.token,data:{fullName:user.user.fullName,phone:user.user.phone,avatarUrl:image.url}});assert.equal((await request('/api/auth/me',{token:user.token})).avatarUrl,image.url);const served=await fetch(base+image.url);assert.equal(served.status,200);assert.deepEqual(Buffer.from(await served.arrayBuffer()),bytes);});
 console.log('All automated API acceptance checks passed. Browser refresh and restart checks remain in README.');
}catch(e){reports.push({name:'Failure',status:'FAIL',message:e.message});console.error(e);process.exitCode=1;}finally{fs.mkdirSync('verification',{recursive:true});fs.writeFileSync('verification/e2e-report.json',JSON.stringify({testedAt:new Date().toISOString(),base,reports},null,2));}
