package vn.cinema;
import org.junit.jupiter.api.*;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.test.context.bean.override.mockito.MockitoBean;import vn.cinema.app.Application;import vn.cinema.client.BookingClient;import vn.cinema.service.PaymentService;import vn.cinema.service.PayOSClient;import vn.cinema.repository.PaymentRepository;import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.ObjectNode;import java.time.Instant;import static org.mockito.Mockito.*;import static org.assertj.core.api.Assertions.*;
@SpringBootTest(classes=Application.class)
class PaymentTest{
 @Autowired PaymentService service;@Autowired PaymentRepository payments;@Autowired ObjectMapper mapper;@MockitoBean BookingClient bookings;@MockitoBean PayOSClient payos;ObjectNode booking;
 @BeforeEach void setup(){payments.deleteAll();reset(bookings,payos);booking=mapper.createObjectNode();booking.put("id",301);booking.put("userId",71);booking.put("status","PENDING");booking.put("totalAmount",210000);booking.put("bookingCode","TEST-BOOKING");booking.put("expiredAt",Instant.now().plusSeconds(600).toString());when(bookings.get(301)).thenAnswer(i->booking.deepCopy());when(bookings.confirm(301)).thenAnswer(i->{booking.put("status","CONFIRMED");booking.put("confirmedAt",Instant.now().toString());return booking.deepCopy();});when(bookings.cancel(301)).thenAnswer(i->{booking.put("status","CANCELLED");return booking.deepCopy();});when(payos.configured()).thenReturn(true);var link=new PayOSClient.Link(301,"LINK-301","PENDING","https://pay.payos.vn/web/LINK-301","QR-CONTENT","8820529070","NGUYEN VAN A",0);when(payos.create(anyLong(),anyLong(),anyLong(),anyString(),anyLong())).thenReturn(link);when(payos.get(301)).thenReturn(link);}
 @Test void createThenResumeReturnsSamePendingPayment(){var p=service.create(301,71,false);assertThat(service.create(301,71,false).id).isEqualTo(p.id);assertThat(service.byBooking(301,71,false).transactionCode).isEqualTo(p.transactionCode);assertThat(payments.count()).isEqualTo(1);assertThat(p.amount).isEqualByComparingTo("210000");}
 @Test void generatedOrderCodeFitsPayOSSafeInteger(){service.create(301,71,false);var code=org.mockito.ArgumentCaptor.forClass(Long.class);verify(payos).create(code.capture(),eq(301L),anyLong(),anyString(),anyLong());assertThat(code.getValue()).isPositive().isLessThanOrEqualTo(9_007_199_254_740_991L);}
 @Test void repeatedAdminConfirmCallsBookingOnce(){var p=service.create(301,71,false);for(int i=0;i<5;i++)assertThat(service.confirmByAdmin(p.id).status).isEqualTo("SUCCESS");verify(bookings,times(1)).confirm(301);assertThat(payments.count()).isEqualTo(1);}
 @Test void reconcilesAfterRemoteConfirmCommittedButLocalSaveDidNot(){var p=service.create(301,71,false);booking.put("status","CONFIRMED");booking.put("confirmedAt",Instant.now().toString());service.reconcile(p.id);assertThat(service.get(p.id,71,false).status).isEqualTo("SUCCESS");verify(bookings,never()).confirm(301);}
 @Test void paidStatusFromPayOSAutomaticallyConfirmsBooking(){var p=service.create(301,71,false);when(payos.get(301)).thenReturn(new PayOSClient.Link(301,"LINK-301","PAID","https://pay.payos.vn/web/LINK-301","QR-CONTENT","8820529070","NGUYEN VAN A",210000));assertThat(service.get(p.id,71,false).status).isEqualTo("SUCCESS");verify(bookings).confirm(301);}
 @Test void expiredBookingMakesPaymentFailed(){var p=service.create(301,71,false);booking.put("status","EXPIRED");assertThat(service.get(p.id,71,false).status).isEqualTo("FAILED");assertThatThrownBy(()->service.confirmByAdmin(p.id)).hasMessageContaining("hiệu lực");}
 @Test void ownerCheckAndCancelReleaseBooking(){var p=service.create(301,71,false);assertThatThrownBy(()->service.get(p.id,72,false)).hasMessageContaining("quyền");assertThat(service.cancel(p.id,71,false).status).isEqualTo("FAILED");verify(payos).cancel(301);verify(bookings).cancel(301);}
}
