package vn.cinema.service;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import vn.cinema.entity.*;import vn.cinema.repository.*;import vn.cinema.client.*;import vn.cinema.dto.BookingRequest;import vn.cinema.exception.Problem;import com.fasterxml.jackson.databind.*;import java.time.*;import java.math.BigDecimal;import java.util.*;
@Service public class BookingService{private final BookingRepository bookings;private final SeatReservationRepository reservations;private final ShowtimeClient showtimes;private final CinemaClient cinemas;private final ObjectMapper mapper;
 public BookingService(BookingRepository b,SeatReservationRepository r,ShowtimeClient s,CinemaClient c,ObjectMapper m){bookings=b;reservations=r;showtimes=s;cinemas=c;mapper=m;}
 @Transactional public Booking create(long userId,BookingRequest request){if(new HashSet<>(request.seatIds()).size()!=request.seatIds().size())throw new Problem(400,"Danh sách ghế bị trùng");JsonNode detail=showtimes.open(request.showtimeId());JsonNode show=detail.path("showtime");if(!show.path("status").asText().equals("AVAILABLE")||!LocalDateTime.parse(show.path("startAt").asText()).isAfter(LocalDateTime.now()))throw new Problem(409,"Suất chiếu không còn nhận đặt vé");if(!detail.path("room").path("status").asText().equals("ACTIVE")||!detail.path("cinema").path("status").asText().equals("ACTIVE"))throw new Problem(409,"Rạp hoặc phòng đã ngừng hoạt động");
 var available=cinemas.seats(show.path("roomId").asLong());var b=new Booking();b.bookingCode="MV"+UUID.randomUUID().toString().replace("-","").substring(0,16).toUpperCase(Locale.ROOT);b.userId=userId;b.showtimeId=request.showtimeId();b.status="PENDING";b.expiredAt=Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS).plusSeconds(600);b.snapshot=detail.toString();b.subtotal=BigDecimal.ZERO;
 for(Long id:request.seatIds()){var seat=available.stream().filter(s->s.path("id").asLong()==id).findFirst().orElseThrow(()->new Problem(400,"Ghế không thuộc phòng của suất chiếu"));if(!seat.path("status").asText().equals("ACTIVE"))throw new Problem(409,"Ghế đang bị khóa");var line=new BookingSeat();line.showtimeId=b.showtimeId;line.seatId=id;line.seatName=seat.path("rowName").asText()+seat.path("seatNumber").asInt();line.seatType=seat.path("seatType").asText();line.unitPrice=TicketPricing.price(show.path("basePrice").decimalValue(),line.seatType);b.seats.add(line);b.subtotal=b.subtotal.add(line.unitPrice);}
 b.totalAmount=b.subtotal;bookings.saveAndFlush(b);for(var line:b.seats){var reservation=new SeatReservation();reservation.bookingId=b.id;reservation.showtimeId=b.showtimeId;reservation.seatId=line.seatId;reservations.save(reservation);}reservations.flush();return b;}
 @Transactional public Booking get(long id){var b=bookings.lock(id).orElseThrow(Problem::missing);expire(b);return b;}
 @Transactional public Booking cancel(long id,long userId,boolean admin){var b=bookings.lock(id).orElseThrow(Problem::missing);owner(b,userId,admin);expire(b);if(b.status.equals("CANCELLED")||b.status.equals("EXPIRED"))return b;if(!b.status.equals("PENDING"))throw new Problem(409,"Vé đã xác nhận không thể tự hủy");b.status="CANCELLED";b.cancelledAt=Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS);reservations.deleteByBookingId(id);return b;}
 @Transactional public Booking confirm(long id){var b=bookings.lock(id).orElseThrow(Problem::missing);expire(b);if(b.status.equals("PENDING")){b.status="CONFIRMED";b.confirmedAt=Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS);}return b;}
 private void expire(Booking b){if(b.status.equals("PENDING")&&!b.expiredAt.isAfter(Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS))){b.status="EXPIRED";reservations.deleteByBookingId(b.id);}}
 @Transactional public void expireOne(long id){bookings.lock(id).ifPresent(this::expire);}
 public List<Long> expired(){return bookings.findByStatusAndExpiredAtBefore("PENDING",Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS)).stream().map(b->b.id).toList();}
 public List<Booking> list(long userId,boolean admin){return admin?bookings.findAll().stream().sorted(Comparator.comparing((Booking b)->b.createdAt).reversed()).toList():bookings.findByUserIdOrderByCreatedAtDesc(userId);}
 public static void owner(Booking b,long userId,boolean admin){if(!admin&&!b.userId.equals(userId))throw new Problem(403,"Bạn không có quyền xem vé này");}
 public Map<String,Object> view(Booking b){var map=mapper.convertValue(b,new com.fasterxml.jackson.core.type.TypeReference<Map<String,Object>>(){});try{map.put("details",mapper.readTree(b.snapshot));}catch(com.fasterxml.jackson.core.JsonProcessingException e){throw new IllegalStateException("Booking snapshot cannot be read",e);}return map;}
 public boolean used(long id){return bookings.existsByShowtimeId(id);}
 public Object seatMap(long showtimeId){var detail=showtimes.details(showtimeId);var show=detail.path("showtime");var taken=reservations.findByShowtimeId(showtimeId);var result=new ArrayList<Map<String,Object>>();for(var s:cinemas.seats(show.path("roomId").asLong())){var item=mapper.convertValue(s,new com.fasterxml.jackson.core.type.TypeReference<Map<String,Object>>(){});String state=s.path("status").asText().equals("ACTIVE")?"AVAILABLE":"LOCKED";var reservation=taken.stream().filter(t->t.seatId==s.path("id").asLong()).findFirst();if(reservation.isPresent()){var booking=bookings.findById(reservation.get().bookingId).orElseThrow();state=booking.status.equals("CONFIRMED")?"SOLD":"HELD";}item.put("availability",state);item.put("unitPrice",TicketPricing.price(show.path("basePrice").decimalValue(),s.path("seatType").asText()));result.add(item);}return Map.of("details",detail,"seats",result,"serverTime",Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS));}
 public List<Booking> unsent(){return bookings.findByStatusAndNotifiedFalse("CONFIRMED");}@Transactional public void notified(long id){bookings.lock(id).orElseThrow().notified=true;}
}

